version: 1.0.{build}

image: Visual Studio 2019

# environment variables
environment:
  webApiIdentityServer: WebApi/Services/Identity/IdentityServer.API/IdentityServer.API.csproj
  webApiIdentityServerTest: WebApi/Services/Identity/IdentityServer.API.Test/IdentityServer.API.Test.csproj
  webApiIdentityServerIntegrationTest: WebApi/Services/Identity/IdentityServer.API.IntegrationTest/IdentityServer.API.IntegrationTest.csproj

  webApiMeal: WebApi/Services/Meals/Meals.API/Meals.API.csproj
  webApiMealTest: WebApi/Services/Meals/Meals.API.Tests/Meals.API.Tests.csproj
  webApiMealIntegrationTests: WebApi/Services/Meals/Meals.API.IntegrationTests/Meals.API.IntegrationTests.csproj

  token:
    secure: 9uRVSSCcR5LJnvA8wH/AU0w0g3HYu90HhhqxUMuzWbmPlxhyLQC4rGPAGiVV0kYZ

init:
  - cmd: dotnet tool install -g dotnet-sonarscanner

install:
before_build:
  - cmd: dotnet --version
  - cmd: nuget restore
  - cmd: dotnet-sonarscanner begin /k:"zanuccod_FoodTracker" /o:"zanuccod" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login=%token% /d:sonar.cs.opencover.reportsPaths="TestResults/TestResult.xml"
  
build_script:
  - cmd: dotnet build %webApiIdentityServer%
  - cmd: dotnet build %webApiIdentityServerTest%
  - cmd: dotnet build %webApiIdentityServerIntegrationTest%

  - cmd: dotnet build %webApiMeal%
  - cmd: dotnet build %webApiMealTest%
  - cmd: dotnet build %webApiMealIntegrationTests%
  
test_script:
  - cmd: dotnet test %webApiIdentityServerTest% /p:CollectCoverage=true /p:CoverletOutputFormat=json /p:CoverletOutput=../../../../TestResults/TestResult.json --test-adapter-path:. --logger:Appveyor
  - cmd: dotnet test %webApiIdentityServerIntegrationTest% /p:CollectCoverage=true /p:CoverletOutputFormat=json /p:CoverletOutput=../../../../TestResults/TestResult.json /p:MergeWith=../../../../TestResults/TestResult.json
  - cmd: dotnet test %webApiMealTest% /p:CollectCoverage=true /p:CoverletOutputFormat=json /p:CoverletOutput=../../../../TestResults/TestResult.json /p:MergeWith=../../../../TestResults/TestResult.json
  - cmd: dotnet test %webApiMealIntegrationTests% /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=../../../../TestResults/TestResult.xml /p:MergeWith=../../../../TestResults/TestResult.json

on_finish:
  - cmd: dotnet-sonarscanner end /d:sonar.login=%token%
  
deploy: off